package gba

import (
	"acheron-save-parser/utils"
	"regexp"
	"strings"
)

type GbaConfig struct {
	Match string
	// abilities

	AbilityInfoSize int // size in bytes of Ability struct in include/pokemon.h
	/* In rhh header */ // AbilitiesOffset int // gAbilitiesInfo from .map
	/* In rhh header */ // AbilitiesCount  int // ABILITIES_COUNT in include/constants/abilities.h
	// items

	ItemInfoSize int // size in bytes of Item struct in include/item.h
	/* In rhh header */ // ItemsOffset int // gItemsInfo from .map
	/* In rhh header */ // ItemsCount  int // ITEMS_COUNT in include/constants/items.h
	// moves

	MoveInfoSize int // size in bytes of MoveInfo struct in include/move.h
	/* In rhh header */ // MovesOffset int // gMovesInfo from .map
	/* In rhh header */ // MovesCount int // MOVES_COUNT_ALL in include/constants/moves.h

	MoveAdditionalEffectsSize int // size in bytes of AdditionalEffect struct in include/move.h
	// natures

	NaturesOffset  int // gNaturesInfo from .map
	NatureInfoSize int // size in bytes of NatureInfo struct in include/pokemon.h
	NaturesCount   int // NUM_NATURES in include/constants/pokemon.h
	// species

	PokemonNameLength int // POKEMON_NAME_LENGTH in include/constants/global.h
	SpeciesInfoSize   int // size in bytes of SpeciesInfo struct in include/pokemon.h
	/* In rhh header */ // SpeciesOffset int // gSpeciesInfo from .map
	/* In rhh header */ // SpeciesCount int // NUM_SPECIES in include/constants/species.h
	// wild encounters

	WildEncountersOffset int // gWildMonHeaders from .map
	WildEncounterSize    int // size in bytes of WildPokemonHeader struct in include/wild_encounter.h
	/* has sentinel */ // WildEncountersCount  int // array length of gWildMonHeaders in src/data/wild_encounters.h (autogenerated)

	WildPokemonSize int // size in bytes of WildPokemon struct in include/wild_encounter.h
	// region map

	MapGroupsOffset       int   // gMapGroups from .map
	MapGroupSize          int   // size in bytes of MapHeader struct in include/global.fieldmap.h
	MapGroupCounts        []int // literal MAP_GROUP_COUNT array in src/data/map_group_count.h (autogenerated)
	RegionLocationsOffset int   // gRegionMapEntries from .map
	RegionLocationSize    int   // size in bytes of RegionMapLocation struct in include/region_map.h
	RegionLocationsCount  int   // array length of gRegionMapEntries in src/data/region_map/region_map_entries.h (autogenerated)
}

var (
	LatestVersion = "1.11.1"
	versionConfig = map[string]GbaConfig{
		LatestVersion: GbaConfig{
			AbilityInfoSize:           utils.AlignPointer(28),
			ItemInfoSize:              utils.AlignPointer(80),
			MoveInfoSize:              utils.AlignPointer(48),
			MoveAdditionalEffectsSize: utils.AlignPointer(4),
			NatureInfoSize:            utils.AlignPointer(20),
			NaturesOffset:             0x086cf29c - POINTER_OFFSET,
			NaturesCount:              25,
			PokemonNameLength:         13,
			SpeciesInfoSize:           utils.AlignPointer(260),
			WildEncountersOffset:      0x08edd49c - POINTER_OFFSET,
			WildEncounterSize:         utils.AlignPointer(24),
			WildPokemonSize:           utils.AlignPointer(4),
			MapGroupsOffset:           0x08fccd8c - POINTER_OFFSET,
			MapGroupSize:              utils.AlignPointer(27),
			MapGroupCounts:            []int{57, 5, 5, 6, 7, 8, 9, 7, 7, 14, 8, 17, 10, 23, 13, 15, 15, 2, 2, 2, 3, 1, 1, 1, 108, 61, 89, 2, 1, 13, 1, 1, 3, 1, 0},
			RegionLocationsOffset:     0x08d9b1d0 - POINTER_OFFSET,
			RegionLocationSize:        utils.AlignPointer(8),
			RegionLocationsCount:      213,
		},
		"1.11.1-a": GbaConfig{
			AbilityInfoSize:           utils.AlignPointer(28),
			ItemInfoSize:              utils.AlignPointer(80),
			MoveInfoSize:              utils.AlignPointer(48),
			MoveAdditionalEffectsSize: utils.AlignPointer(4),
			NatureInfoSize:            utils.AlignPointer(20),
			NaturesOffset:             0x086d1aa8 - POINTER_OFFSET,
			NaturesCount:              25,
			PokemonNameLength:         13,
			SpeciesInfoSize:           utils.AlignPointer(260),
			WildEncountersOffset:      0x08ee7c40 - POINTER_OFFSET,
			WildEncounterSize:         utils.AlignPointer(24),
			WildPokemonSize:           utils.AlignPointer(4),
			MapGroupsOffset:           0x08fd8a30 - POINTER_OFFSET,
			MapGroupSize:              utils.AlignPointer(27),
			MapGroupCounts:            []int{58, 5, 5, 6, 7, 8, 9, 7, 7, 14, 8, 17, 10, 23, 13, 15, 15, 2, 2, 2, 3, 1, 1, 1, 108, 61, 89, 2, 1, 13, 1, 1, 3, 1, 0},
			RegionLocationsOffset:     0x08da4f98 - POINTER_OFFSET,
			RegionLocationSize:        utils.AlignPointer(8),
			RegionLocationsCount:      214,
		},
		"1.10.x": GbaConfig{},
		"1.9.x": GbaConfig{
			AbilityInfoSize:           utils.AlignPointer(28),
			ItemInfoSize:              utils.AlignPointer(80),
			MoveInfoSize:              utils.AlignPointer(52),
			MoveAdditionalEffectsSize: utils.AlignPointer(4),
			NatureInfoSize:            utils.AlignPointer(20),
			NaturesOffset:             0x086923f0 - POINTER_OFFSET,
			NaturesCount:              25,
			PokemonNameLength:         13,
			SpeciesInfoSize:           utils.AlignPointer(216),
			WildEncounterSize:         utils.AlignPointer(20),
			WildPokemonSize:           utils.AlignPointer(4),
			WildEncountersOffset:      0x08de747c - POINTER_OFFSET,
			MapGroupsOffset:           0x08edb4f0 - POINTER_OFFSET,
			MapGroupSize:              utils.AlignPointer(27),
			MapGroupCounts:            []int{58, 5, 5, 6, 7, 8, 9, 7, 7, 14, 8, 17, 10, 23, 13, 15, 15, 2, 2, 2, 3, 1, 1, 1, 108, 61, 89, 2, 1, 13, 1, 1, 3, 1, 0},
			RegionLocationsOffset:     0x08cf93b4 - POINTER_OFFSET,
			RegionLocationSize:        utils.AlignPointer(8),
			RegionLocationsCount:      215,
		},
	}
)

// GetGbaConfig returns the GBA config for the given version
// If the version is not found, it returns the latest version config
// VersionConfig is a map of version strings to their corresponding GBA config
// 1.x.x is valid syntax, it will return the latest 1.x.x version config
// or the latest overall if a 1.x.x pattern is not matched
func GetGbaConfig(version string) GbaConfig {
	if config, ok := versionConfig[version]; ok {
		config.Match = version
		return config
	}

	if version == "" {
		conf := versionConfig[LatestVersion]
		conf.Match = LatestVersion
		return conf
	}

	// Pattern matching for x.x.x or 1.x.x
	parts := strings.Split(version, ".")
	if len(parts) >= 2 {
		var latestMatch string
		for v := range versionConfig {

			pattern := strings.ReplaceAll(v, "x", `\d+`)
			re := regexp.MustCompile(pattern)
			if re.MatchString(version) {
				if latestMatch == "" || v > latestMatch {
					latestMatch = v
				}
			}
		}

		if latestMatch != "" {
			conf := versionConfig[latestMatch]
			conf.Match = latestMatch
			return conf
		}
	}

	// Return latest version config if no match found
	conf := versionConfig[LatestVersion]
	conf.Match = LatestVersion
	return conf
}
